# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nithin2023

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ed5cf39b24d8448aafdaf0251f339b3d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_15a632cb4bc04e6c878d0ad3c26b2479 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ed5cf39b24d8448aafdaf0251f339b3d }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nithin2023'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0401bf85c09943129ae9f1ff16d8082c }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ed5cf39b24d8448aafdaf0251f339b3d }}/appsvc/staticsite:${{ github.sha }}'